"""
Report generation service.

Called by tasks.chain_b.task_generate_report at the end of Chain B.

FLOW:
  1. build_report_context(case_id, db) — assembles full dict from PostgreSQL
  2. _render_template(context)          — Jinja2 → HTML string
  3. WeasyPrint → PDF bytes             — on failure, save JSON only (non-fatal)
  4. upload_report_pdf / _json → S3
  5. Insert Report row in DB

DRT STAY GATE:
  If drt_interim_stay_granted == True in case facts, override recommendation
  to DO_NOT_PROCEED_CRITICAL regardless of computed score.
"""

from __future__ import annotations

import json
import uuid
from datetime import datetime
from decimal import Decimal
from typing import Optional

from jinja2 import Environment, FileSystemLoader, select_autoescape
from sqlalchemy.orm import Session

from app.config import settings

# ─── DISPLAY MAPS ────────────────────────────────────────────────────────────

SEVERITY_TO_LABEL: dict[str, str] = {
    "FATAL": "Fatal",
    "ABSOLUTE_BAR": "Absolute Bar",
    "CURABLE": "Curable",
    "MINOR": "Minor",
    "ADVISORY": "Advisory",
    "REVIEW_REQUIRED": "Review Required",
    "UNKNOWN": "Unknown",
}

GROUND_CODE_NAMES: dict[str, str] = {
    "G01_DEMAND_NOTICE": "Demand Notice (Sec 13(2))",
    "G02_SYMBOLIC_POSSESSION": "Symbolic Possession (Sec 13(4))",
    "G03_PHYSICAL_POSSESSION": "Physical Possession (Sec 14)",
    "G04_VALUATION": "Valuation",
    "G05_PUBLICATION": "Sale Publication (Rule 8)",
    "G06_RESERVE_PRICE": "Reserve Price (Rule 9)",
    "G07_DRT_STAY": "DRT Interim Stay",
    "G08_NPA_CLASSIFICATION": "NPA Classification",
    "G09_MSME_SPECIAL": "MSME Special Provisions",
}

MODULE_NAMES: dict[str, str] = {
    "m1_demand": "Demand Notice",
    "m2_symbolic": "Symbolic Possession",
    "m3_physical": "Physical Possession",
    "m4_valuation": "Valuation",
    "m5_publication": "Sale Publication",
    "m6_reserve": "Reserve Price",
    "m7_drt": "DRT Proceedings",
    "m8_npa": "NPA Classification",
    "m9_msme": "MSME Provisions",
}

RECOMMENDATION_DISPLAY: dict[str, str] = {
    "PROCEED": "Proceed",
    "PROCEED_WITH_CAUTION": "Proceed with Caution",
    "DO_NOT_PROCEED": "Do Not Proceed",
    "DO_NOT_PROCEED_CRITICAL": "Do Not Proceed — Critical Issues",
}

DISCLAIMER_TEXT = (
    "This report is generated by an AI-assisted legal analysis platform and is intended "
    "solely for internal use by the bank's legal and recovery teams. It does not constitute "
    "legal advice. All recommendations must be reviewed by qualified legal counsel before "
    "any enforcement action is initiated. The platform's analysis is based on the facts "
    "extracted from the uploaded documents and the judgment corpus as of the report date. "
    "Judgments and statutes may have been modified, overruled, or distinguished since the "
    "corpus was last updated. Verify all citations independently."
)


# ─── HELPERS ─────────────────────────────────────────────────────────────────

def _strength_label(score: Optional[float]) -> str:
    if score is None:
        return "Unknown"
    if score >= 0.75:
        return "Strong"
    if score >= 0.50:
        return "Moderate"
    if score >= 0.25:
        return "Weak"
    return "Very Weak"


def _strength_color(score: Optional[float]) -> str:
    if score is None:
        return "#6b7280"
    if score >= 0.75:
        return "#16a34a"
    if score >= 0.50:
        return "#d97706"
    if score >= 0.25:
        return "#dc2626"
    return "#7f1d1d"


def _exposure_label(exposure: Optional[float]) -> str:
    if exposure is None:
        return "Unknown"
    if exposure >= 0.70:
        return "High"
    if exposure >= 0.40:
        return "Medium"
    return "Low"


def _exposure_color(exposure: Optional[float]) -> str:
    if exposure is None:
        return "#6b7280"
    if exposure >= 0.70:
        return "#dc2626"
    if exposure >= 0.40:
        return "#d97706"
    return "#16a34a"


def _score_color(score: Optional[int]) -> str:
    if score is None:
        return "#6b7280"
    if score >= 75:
        return "#16a34a"
    if score >= 50:
        return "#d97706"
    return "#dc2626"


def _compliance_band(score: Optional[int]) -> str:
    if score is None:
        return "Unknown"
    if score >= 75:
        return "Compliant"
    if score >= 50:
        return "Partial"
    return "Non-Compliant"


def _calculate_compliance(compliance_results: list[dict]) -> int:
    if not compliance_results:
        return 0
    passes = sum(1 for r in compliance_results if r.get("status") == "PASS")
    return int((passes / len(compliance_results)) * 100)


def _calculate_exposure(ground_scores: list[dict]) -> float:
    if not ground_scores:
        return 0.0
    scores = [g.get("ground_strength") for g in ground_scores if g.get("ground_strength") is not None]
    if not scores:
        return 0.0
    return round(sum(scores) / len(scores), 2)


def _get_statute_text(db: Session, case_id: str, rule_id: str) -> Optional[str]:
    from app.models.db import CaseStatute
    row = db.query(CaseStatute).filter_by(case_id=case_id, rule_id=rule_id).first()
    return row.statute_text if row else None


def _get_authority_for_rule(rule_id: str) -> Optional[str]:
    from app.tasks.chain_b import RULE_TO_GROUND_MAP
    return RULE_TO_GROUND_MAP.get(rule_id)


def _get_applicable_judgments_by_ground(db: Session, case_id: str) -> dict[str, list[dict]]:
    """Bulk-fetches applicability + judgment rows for the whole case in two
    queries, grouped by ground_code — avoids an N+1 (and nested N+1) when
    called once per ground in build_report_context."""
    from app.models.db import JudgmentApplicability, Judgment

    applicability_rows = (
        db.query(JudgmentApplicability)
        .filter_by(case_id=case_id)
        .filter(JudgmentApplicability.status.in_(["APPLICABLE", "PARTIAL", "SIMILARITY_RETRIEVED"]))
        .all()
    )
    judgment_ids = {row.judgment_id for row in applicability_rows}
    judgments_by_id = {}
    if judgment_ids:
        judgments_by_id = {
            j.id: j for j in db.query(Judgment).filter(Judgment.id.in_(judgment_ids)).all()
        }

    by_ground: dict[str, list[dict]] = {}
    for row in applicability_rows:
        j = judgments_by_id.get(row.judgment_id)
        if not j:
            continue
        by_ground.setdefault(row.ground_code, []).append({
            "citation": j.citation,
            "title": j.title,
            "court": j.court,
            "favor": j.favor,
            "holding_summary": j.holding_summary,
            "status": row.status,
            "reason": row.reason,
        })
    return by_ground


# ─── CONTEXT BUILDER ──────────────────────────────────────────────────────────

def build_report_context(case_id: str, db: Session) -> dict:
    from app.models.db import (
        Case, CaseFact, ComplianceResult, SAGround,
        GroundScore, JudgmentApplicability, Report, Judgment,
    )

    case = db.query(Case).filter_by(id=case_id).first()
    if not case:
        raise ValueError(f"Case {case_id} not found")

    facts_rows = db.query(CaseFact).filter_by(case_id=case_id).all()
    facts = {f.field_name: f.field_value for f in facts_rows}

    compliance_rows = db.query(ComplianceResult).filter_by(case_id=case_id).all()
    compliance_results = [
        {
            "rule_id": r.rule_id,
            "module": r.module,
            "status": r.status,
            "severity": r.severity,
            "message": r.message,
            "detail_json": r.detail_json,
            "module_display": MODULE_NAMES.get(r.module, r.module),
            "severity_display": SEVERITY_TO_LABEL.get(r.severity or "", r.severity or ""),
            "statute_text": _get_statute_text(db, case_id, r.rule_id),
            "authority": _get_authority_for_rule(r.rule_id),
        }
        for r in compliance_rows
    ]

    sa_ground_rows = db.query(SAGround).filter_by(case_id=case_id).all()
    ground_score_rows = db.query(GroundScore).filter_by(case_id=case_id).all()
    ground_score_map = {g.ground_code: g for g in ground_score_rows}

    judgments_by_ground = _get_applicable_judgments_by_ground(db, case_id)

    ground_scores = []
    for g in sa_ground_rows:
        gs = ground_score_map.get(g.ground_code)
        entry = {
            "ground_code": g.ground_code,
            "ground_display": GROUND_CODE_NAMES.get(g.ground_code, g.ground_code),
            "factual_score": gs.factual_score if gs else None,
            "judicial_score": gs.judicial_score if gs else None,
            "ground_strength": gs.ground_strength if gs else None,
            "corpus_total": gs.corpus_total if gs else 0,
            "corpus_borrower_wins": gs.corpus_borrower_wins if gs else 0,
            "corpus_bank_wins": gs.corpus_bank_wins if gs else 0,
            "corpus_confidence": gs.corpus_confidence if gs else "NO_DATA",
            "full_corpus_total": gs.full_corpus_total if gs else 0,
            "full_corpus_borrower_wins": gs.full_corpus_borrower_wins if gs else 0,
            "full_corpus_bank_wins": gs.full_corpus_bank_wins if gs else 0,
            "strength_label": _strength_label(gs.ground_strength if gs else None),
            "strength_color": _strength_color(gs.ground_strength if gs else None),
            "judgments": judgments_by_ground.get(g.ground_code, []),
        }
        ground_scores.append(entry)

    compliance_score = _calculate_compliance(compliance_results)
    litigation_exposure = _calculate_exposure(ground_scores)

    # Group compliance results by module
    module_results: dict[str, list] = {}
    for r in compliance_results:
        module_results.setdefault(r["module"], []).append(r)

    red_flags = [r for r in compliance_results if r["status"] == "FAIL" and r["severity"] in ("FATAL", "ABSOLUTE_BAR")]

    recommendation = case.pipeline_stage
    latest_report = db.query(Report).filter_by(case_id=case_id).order_by(Report.generated_at.desc()).first()
    if latest_report and latest_report.recommendation:
        recommendation = latest_report.recommendation

    # DRT stay gate — overrides everything
    drt_stay = str(facts.get("drt_interim_stay_granted") or "").lower()
    if drt_stay in ("true", "yes", "1"):
        recommendation = "DO_NOT_PROCEED_CRITICAL"

    # ── Prayer clause + third party context (v5.4) ────────────────────────────
    def _truthy(v) -> bool:
        return str(v or "").lower() in ("true", "yes", "1")

    prayer_context = {
        "sa_applicant_type":            facts.get("sa_applicant_type"),
        "challenges_demand_notice":     _truthy(facts.get("challenges_demand_notice")),
        "challenges_possession_notice": _truthy(facts.get("challenges_possession_notice")),
        "challenges_sale_notice":       _truthy(facts.get("challenges_sale_notice")),
        "challenges_auction":           _truthy(facts.get("challenges_auction")),
        "challenges_demand_amount":     _truthy(facts.get("challenges_demand_amount")),
        "interim_stay_prayed":          _truthy(facts.get("interim_stay_prayed")),
        "interim_stay_granted":         _truthy(facts.get("interim_stay_granted")),
        "prayer_scope_covers_current_measure": (
            facts.get("prayer_scope_covers_current_measure") is None
            or _truthy(facts.get("prayer_scope_covers_current_measure"))
        ),
        "ats_advance_paid":             facts.get("ats_advance_paid"),
        "ats_date":                     facts.get("ats_date"),
        "ats_simultaneous_mortgage":    _truthy(facts.get("ats_simultaneous_mortgage")),
    }

    return {
        "case": {
            "id": str(case.id),
            "bank_id": str(case.bank_id),
            "borrower_name": case.borrower_name,
            "case_ref": case.case_ref,
            "drt_case_number": case.drt_case_number,
            "drt_bench": case.drt_bench,
            "property_description": case.property_description,
            "loan_account_number": case.loan_account_number,
            "principal_amount": float(case.principal_amount) if case.principal_amount else None,
            "status": case.status,
            "judgment_coverage_alerts": case.judgment_coverage_alerts or [],
        },
        "facts": facts,
        "compliance_results": compliance_results,
        "module_results": module_results,
        "ground_scores": ground_scores,
        "compliance_score": compliance_score,
        "compliance_band": _compliance_band(compliance_score),
        "score_color": _score_color(compliance_score),
        "litigation_exposure": litigation_exposure,
        "exposure_label": _exposure_label(litigation_exposure),
        "exposure_color": _exposure_color(litigation_exposure),
        "recommendation": recommendation,
        "recommendation_display": RECOMMENDATION_DISPLAY.get(recommendation or "", recommendation or ""),
        "red_flags": red_flags,
        "total_grounds": len(ground_scores),
        "grounds_with_precedent": sum(1 for g in ground_scores if g["judgments"]),
        "coverage_alerts": case.judgment_coverage_alerts or [],
        "report_date": datetime.utcnow().strftime("%d %B %Y"),
        "disclaimer": DISCLAIMER_TEXT,
        "drt_stay_active": drt_stay in ("true", "yes", "1"),
        # SVG gauge constants
        "gauge_circumference": 326.7,
        # Prayer clause + third party context (v5.4)
        **prayer_context,
    }


# ─── TEMPLATE RENDERING ───────────────────────────────────────────────────────

def _currency_filter(value) -> str:
    if value is None:
        return "N/A"
    try:
        v = float(value)
        if v >= 1e7:
            return f"₹{v/1e7:.2f} Cr"
        if v >= 1e5:
            return f"₹{v/1e5:.2f} L"
        return f"₹{v:,.2f}"
    except (TypeError, ValueError):
        return str(value)


def _pct_filter(value) -> str:
    if value is None:
        return "N/A"
    try:
        return f"{float(value) * 100:.1f}%"
    except (TypeError, ValueError):
        return str(value)


def _date_fmt_filter(value) -> str:
    if value is None:
        return "N/A"
    if isinstance(value, str):
        return value
    if isinstance(value, datetime):
        return value.strftime("%d %B %Y")
    return str(value)


def _render_template(context: dict) -> str:
    env = Environment(
        loader=FileSystemLoader(settings.report_template_dir),
        autoescape=select_autoescape(["html", "j2"]),
    )
    env.filters["currency"] = _currency_filter
    env.filters["pct"] = _pct_filter
    env.filters["date_fmt"] = _date_fmt_filter
    template = env.get_template("report.html.j2")
    return template.render(**context)


# ─── MAIN ENTRY POINT ────────────────────────────────────────────────────────

def generate_report(case_id: str, user_id: str) -> dict:
    """
    Full report generation pipeline.
    Returns dict with keys: report_id, pdf_url, json_s3_key.

    WeasyPrint failure is non-fatal — saves JSON only, pdf_url=None.
    """
    from app.models.db import Report, SyncSessionLocal
    from app.services.storage import upload_report_pdf, upload_report_json

    report_id = str(uuid.uuid4())

    with SyncSessionLocal() as db:
        context = build_report_context(case_id, db)
        html_str = _render_template(context)

        # PDF generation — non-fatal on failure
        pdf_url: Optional[str] = None
        try:
            from weasyprint import HTML
            pdf_bytes = HTML(string=html_str).write_pdf()
            pdf_url = upload_report_pdf(pdf_bytes, case_id, report_id)
        except Exception as exc:
            import logging
            logging.getLogger(__name__).warning(
                "WeasyPrint PDF generation failed for case=%s: %s — saving JSON only",
                case_id, exc
            )

        report_json = json.dumps(context, default=str)
        json_s3_key = upload_report_json(report_json, case_id, report_id)

        report = Report(
            id=uuid.UUID(report_id),
            case_id=uuid.UUID(case_id),
            compliance_score=context.get("compliance_score"),
            litigation_exposure=context.get("litigation_exposure"),
            recommendation=context.get("recommendation"),
            report_json=context,
            pdf_url=pdf_url,
            generated_by=uuid.UUID(user_id) if user_id else None,
        )
        db.add(report)
        db.commit()

    return {"report_id": report_id, "pdf_url": pdf_url, "json_s3_key": json_s3_key}
